### ISSUE TITLE
Enhancements to the instructions on how to install

### ISSUE THREAD

**Issue by teranders** [PhotoBackup/server-bottle#15]
On a clean installed Ubuntu 14.04.4 LTS I had to first install pip3:
`sudo apt-get install python3-pip`

After troubleshooting the forst installation, I found that it failed due to a missing library (libffi-dev) which I also had to install:
`sudo apt-get install libffi-dev`

I then issued the following command to successfully install using Python 3:
`pip3 install photobackup_bottle`

Also, it's stated on the top that it's an Python3 implementation, but for me (maybe I just need new glasses ;-)) the fact that it required Python3 didn't reach my attention. Maybe a requirements section could be added with this and the missing library?

**Comment by stephanepechard** [comment]
I added a `Requirements` section in the `README.md` file in ac31fd14d5841362c7829a5640558aa9c37512e8
Thanks for your input
