### ISSUE TITLE
IO error from bottle when file already exists

### ISSUE THREAD

**Issue by teranders** [PhotoBackup/server-bottle#16]
When the client (standard android client 0.80) tries to upload a photo that already exists, but is of wrong filesize the server tries to save this file (overwrite).
This fails with the following error in the console (server side):
`192.168.10.144 - - [17/Mar/2016 22:07:03] "POST / HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.4/dist-packages/photobackup_bottle/photobackup.py", line 131, in
save_image
    upfile.save(path)
  File "/usr/local/bin/bottle.py", line 2392, in save
    raise IOError('File exists.')
OSError: File exists.
192.168.10.144 - - [17/Mar/2016 22:07:04] "POST / HTTP/1.1" 500 745`

The client will then be (probably) get HTTP error 500 on further upload tries (since nothing happens - the upload queue stops).
I solved this by changing line 131 in photobackup.py. I added the overwrite parameter 'True':

`upfile.save(path, True) # teranders: added 'True' to the overwrite parameter in Bottle`

**Comment by stephanepechard** [comment]
I'm very surprised by this as there is a try/catch on [this](https://github.com/PhotoBackup/server-bottle/blob/master/photobackup_bottle/photobackup.py#L131). Maybe it is because it waits for an IOError and you get an OSError?
Will try to reproduce and fix this during the week-end.
Thanks

**Comment by stephanepechard** [comment]
Just switch from IOError to OSError, could you give it a try? I'll release a new version if it ok for you.
Thanks
