### ISSUE TITLE
Fix to accept external connections

### ISSUE THREAD

**Issue by dmpop** [PhotoBackup/server-bottle#2]
To make the server work with my Android device, I had to change the following line:

```
run(reloader=True) line and change it to
```

to:

```
run(host="0.0.0.0", port=8080, reloader=True)
```

I'm not sure whether it's a feature or a bug, but I thought I'd let you know. :-) Keep up the great work!

**Comment by stephanepechard** [comment]
Yeah, I have to clear a bit these options, and probably set the port out in the configuration file.
Thanks for yout input!

**Comment by stephanepechard** [comment]
Done in version 0.1.0
