### ISSUE TITLE
Sync deletions

### ISSUE THREAD

**Issue by dmpop** [PhotoBackup/server-bottle#4]
It would be great if the server supported sync deletions. So that when certain photos are deleted on the Android device, they are also removed on the server.

**Comment by stephanepechard** [comment]
I'm not sure about this. Sometimes, you erase photos to gain disk space, but you want to keep the backup version.
In fact, I'm not convinced the server should be a complete mirror of what is on the device. The thing is there is no tool to handle pictures on the server (yet) so it could be useful to some users. At least, it should be an option: either you backup everything, either you mirror your device.
Technically, it should not be that difficult server-wise. It's a bit trickier on Android though, to keep a full synced picture library with a remote server.

**Comment by dmpop** [comment]
I see what you mean, and it makes perfect sense. :-) Thank you for your prompt reply.

**Comment by stephanepechard** [comment]
I don't completely unconsider your proposition though, but I think the making of it and the way to propose it to the user should grow a bit more inside my head :-)
Right now, I'm more tempted to develop a simple interface on the server to watch and eventually manage pictures directly on the server. I'm quite convinced the device should only be dumb to backup everything it takes. But maybe my thought on this will evolve in the future...

**Comment by dmpop** [comment]
Actually, having a graphical web interface for the server that makes it possible to view and manage backed up photos is even better than having a syncing functionality.
