### ISSUE TITLE
Gunicorn deployment

### ISSUE THREAD

**Issue by ghost** [PhotoBackup/server-bottle#6]
Could you please provide information how to deploy your app using Gunicorn? I honestly tried but failed

**Comment by stephanepechard** [comment]
I will try to use Gunicorn with it. I don't do it myself actually, I just use NGinx and supervisor to handle it.

**Comment by ghost** [comment]
What kind of supervisor you use? Because Gunicorn is usually used in tandem with Nginx, so may be there is no point in using Gunicorn. Or I am missing something?

**Comment by stephanepechard** [comment]
I use a supervisor called [supervisor](http://supervisord.org/) (I know...), a process control system, that ensures it is started when the server boots, that it restarts if it crashes, and so on. You can use systemd for the same kind of things.
I don't think you particularly need to use Gunicorn though. PB can be used in tandem with Nginx directly. I should probably put some configuration files into the api repo some day...
I tried to use Gunicorn with PB myself, it does not work as is. It lacks a dedicated starting point I think. Try to use Nginx directly, and tell me if you really need Gunicorn.

**Comment by ghost** [comment]
Thanks for clear answer! As I can understand you use Nginx for rewrite (transforming example.com:8420 into example.com/photobackup), yes?

**Comment by stephanepechard** [comment]
Exactly!
It transforms http://127.0.0.1:8420 to a Nginx server name, but today it's more something like http://pb.example.com than http://example.com/photobackup actually.
Go implementation can work this way and I try to make the bottle implementation do as well. I just have to find how :-)
If you're ok, I will close this issue, as I don't think Gunicorn is really needed here.

**Comment by ghost** [comment]
Yeah, sure, thank you for assistance!
