### ISSUE TITLE
Backup stuck

### ISSUE THREAD

**Issue by ghost** [PhotoBackup/server-bottle#7]
Latest client from F-Droid installed (Android 4.4.4, Amazon FirePhone). Server logs report only successful access to the test page:

"POST /test HTTP/1.1" 200 0

The app itself shows the queue (several are marked as Error, the rest - Waiting). How to debug there is the failure point?

**Comment by stephanepechard** [comment]
You can try to plug your phone on a computer to inspect adb logs from PB. Not sure all is there though, I don't know how F-Droid compile it exactly.

**Comment by ghost** [comment]
Bad news - FirPhone doesn't expose any means of debugging as far as I can see
